repos:
  - repo: https://github.com/kynan/nbstripout
    rev: 0.6.0
    hooks:
      - id: nbstripout
  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.5.2
    hooks:
      - id: nbqa
        entry: nbqa unimport
        name: Detect unused imports
        alias: nbqa-unimport
        additional_dependencies: [ unimport==0.12.1, ipython~=8.12.0 ]
        args: [ --check ]
      - id: nbqa-isort
        args: [ --float-to-top ]
        additional_dependencies: [ isort, ipython~=8.12.0 ]